### ISSUE TITLE
Would I be able to fork these policies as a starting point for other hackathons?

### ISSUE THREAD

**Issue by ajyong** [MLH/mlh-policies#113]
Hey MLH, thanks for all you do!  I volunteered for a few MLH hackathons at my local university and saw how much smoother things went with MLH's help.

I see there's been several forks of this repository already, but because this repo has no license, I don't know what constitutes fair use of its contents.  I'm someone who has found themselves starting to organize a virtual hackathon that isn't affiliated with MLH, and would be eternally grateful if these policies could be the starting point for any non-MLH hackathons I help organize.  Until then, I won't do anything silly like copypasta what's here without permission.  Thanks again!

**Comment by theycallmeswift** [comment]
Hey @ajyong! Thanks for reaching out. These policies are public so other organizations can use them to improve their community experience. Our only ask is that you also keep your policies open source and attribute MLH as the original source of the policies. I've added a Creative Commons license to the repo for clarity. 

Let us know if you have any other questions!

**Comment by ajyong** [comment]
Awesome, thanks for clarifying and applying CC4.0-SA. We'll attribute MLH for sure!
