### ISSUE TITLE
Missing College

### ISSUE THREAD

**Issue by unclebinary1001** [MLH/mlh-policies#166]
I am kindly requesting if the university I am attending, **Jackson State University** can be added to the school list repo.

**Comment by BoseSj** [comment]
Added. Review the PR. Then you can close the issue. 😄

**Comment by immattdavison** [comment]
> Added. Review the PR. Then you can close the issue. 😄

It might be better if you include #166 in the PR so that is links to this issue

**Comment by BoseSj** [comment]
I did!
