### ISSUE TITLE
Add college name 

### ISSUE THREAD

**Issue by thecodebox** [MLH/mlh-policies#205]
please add "Fanshawe college" in school list.

**Comment by Anikesh-Singh** [comment]
Can you provide more detailed explanation of the problem?

**Comment by thecodebox** [comment]
my college name is not listed:-
*fanshawe college *and

*Kishinchand Chellaram College*

**Comment by erinosher** [comment]
Hey there 👋 

Thanks for contributing!

We've changed how the `schools.csv` file is maintained and generated, and are no longer accepting pull requests. 

Please check the updated version of the file for your school. If it is still not there, you'll be able to add new schools from within [my.mlh.io](https://my.mlh.io) next week.

Cheers,
Erin and the MLH Team
