### ISSUE TITLE
Duplicate school in `schools.csv`.

### ISSUE THREAD

**Issue by matthewdeguzman** [MLH/mlh-policies#225]
# Description

The file `schools.csv` contains the school "Malvern Preparatory School" twice. Once on line 1023 and again on line 1024.

**Comment by erinosher** [comment]
Hey there 👋 

Thanks for contributing!

We've changed how the `schools.csv` file is maintained and generated, and are no longer accepting pull requests. 

Please check the updated version of the file for your school. If it is still not there, you'll be able to add new schools from within [my.mlh.io](https://my.mlh.io) next week.

Cheers,
Erin and the MLH Team
