### ISSUE TITLE
Schools.md not formatted

### ISSUE THREAD

**Issue by andrewwong97** [MLH/mlh-policies#24]
Is there a way to provide the list as a csv or tsv?

**Comment by Shy** [comment]
@andrewwong97 For now you can view the raw: https://raw.githubusercontent.com/MLH/mlh-policies/master/schools.md . I'll go ahead and migrate it to a CSV tomorrow.

**Comment by andrewwong97** [comment]
Great thanks!

**Comment by Shy** [comment]
Updated via fb400d0df47f2543b784975bfc8607dcc981849d
